### ISSUE TITLE
Seems to handle non `pup` items differently

### ISSUE THREAD

**Issue by ModProg** [traxys/tree-sitter-lalrpop#1]
I'm not totally sure as I don't know anything about the internals of treesitter, but I had these two expressions:
```
pub Expr: i32 = {
    <l:Expr> "+" <r:Factor> => l + r,
    <l:Expr> "-" <r:Factor> => l - r,
    Factor,
};

Factor: i32 = {
    <l:Factor> "*" <r:Term> => l * r,
    <l:Factor> "/" <r:Term> => l / r,
    Term,
};
```
And triggering a `format` using Treesitter in neovim I got:
```
pub Expr: i32 = {
    <l:Expr> "+" <r:Factor> => l + r,
    <l:Expr> "-" <r:Factor> => l - r,
    Factor,
};

Factor: i32 = {
            <l:Factor> "*" <r:Term> => l * r,
            <l:Factor> "/" <r:Term> => l / r,
            Term,
        };
```
For some reason, it handled the bottom one without `pub` poorly.

**Comment by ModProg** [comment]
Actually might just be that I didn't use treesitter to format correctly, I'll close this for now.

**Comment by traxys** [comment]
The tree sitter lalrpop parser ignores most of the whitespace, and I did not define indentation queries

If you are intersted, tree sitter editor support is broken into two parts:
- the parser (this repo) that takes in text and outputs a tree sitter AST
- queries that add information to the AST, and allow to manipulate it. In neovim most of these queries are defined in the nvim-treesitter repo
